### ISSUE TITLE
Kineamtic cut

### ISSUE THREAD

**Issue by mpresill** [mpresill/LatinoAnalysis#3]

**Comment by mpresill** [comment]
kinematic cuts involved in W/Z tagging using the Jet algorithm AK8 PUPPI:

- tau2/tau1 (current value cut = 0.45)
- mass range of soft drop mass (default value [65, 105], and value currently used in steps config [40,250] https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2871)

**Comment by mpresill** [comment]
> kinematic cuts involved in W/Z tagging using the Jet algorithm AK8 PUPPI:
> 
> * tau2/tau1 (current value cut = 0.45)
> * mass range of soft drop mass (default value [65, 105], and value currently used in steps config [40,250] https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2871)

asked to FNAL people, they have no problem using these settings

**Comment by mpresill** [comment]
> kinematic cuts involved in W/Z tagging using the Jet algorithm AK8 PUPPI:
> 
> * tau2/tau1 (current value cut = 0.45)
> * mass range of soft drop mass (default value [65, 105], and value currently used in steps config [40,250] https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2871)

@SiewYan could you please ask your friend in JetMET to bless this cuts? 
@lourdesurda do you have any opinion on that?

**Comment by SiewYan** [comment]
@mpresill , unfortunately he can't say much about this, as those values are determined from an analysis specific study [*]

[*] https://indico.cern.ch/event/779704/contributions/3245276/attachments/1768349/2874166/WtagSF_tau21.pdf

**Comment by mpresill** [comment]
> @mpresill , unfortunately he can't say much about this, as those values are determined from an analysis specific study [*]
> 
> [*] https://indico.cern.ch/event/779704/contributions/3245276/attachments/1768349/2874166/WtagSF_tau21.pdf

Found old studies by Davide, documented here:
https://kbase.valsdav.cloud/public/item/iTVQPj 
where he did not find any evidence of improvement by changing tau2/ta1 from 0.45 default value.
@SiewYan please double check

**Comment by SiewYan** [comment]
> 

Empty page --> https://kbase.valsdav.cloud/public/item/iTVQPj

**Comment by mpresill** [comment]
> Empty page --> https://kbase.valsdav.cloud/public/item/iTVQPj

webpage crashed, he's recovering it later today XD
