### ISSUE TITLE
Cross cleaning FatJet and lepton; CleanedFatJet and CleanedJet

### ISSUE THREAD

**Issue by mpresill** [mpresill/LatinoAnalysis#4]
https://github.com/mpresill/LatinoAnalysis/blob/master/NanoGardener/python/modules/FatJetMaker.py#L45-L46

**Comment by mpresill** [comment]
If we don't use jet ID "LeptonVeto", then the current cleaning DR(lep, fat jet)<0.8, DR(jet, fat jet)<0.8 looks the standard ones, thus should be fine.

**Comment by mpresill** [comment]
The CleanFatJet() functions (https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2871) at ReReco level was run with this inputs:

> jetid=0, minpt=200, maxeta=2.4, max_tau21=0.45, mass_range=[40, 250], over_lepR=0.8, over_jetR=0.8)

so not exactly the default values of "mass_range" of the imported module FatJetMaker.py https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/modules/FatJetMaker.py

**Comment by SiewYan** [comment]
I suggest to close this task? https://github.com/mpresill/LatinoAnalysis/issues/4#issuecomment-991042070 should address the problem
