### ISSUE TITLE
Fatjet ID update

### ISSUE THREAD

**Issue by mpresill** [mpresill/LatinoAnalysis#5]
Information for JetID:
 - https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL#Recommendations_for_the_13_T_AN1
 - https://twiki.cern.ch/twiki/bin/view/CMS/PileupJetIDUL#Recommendations_for_2018_UL_data

**Comment by mpresill** [comment]
@SiewYan can you ask your jet-met contact what is the currently suggested workin point?
Do we need to use the "LepVeto"? if yes this is related with #4

**Comment by SiewYan** [comment]
He confirmed the corresponding AK4's ID is similar to AK8's ID:

```
Please note: For AK8 jets, the corresponding (CHS or PUPPI) AK4 jet ID should be used. 
```

in https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL#Recommendations_for_the_13_T_AN1

**Comment by mpresill** [comment]
> @SiewYan can you ask your jet-met contact what is the currently suggested workin point?
> Do we need to use the "LepVeto"? if yes this is related with #4

Ok, checked. The prescription says:

> We generally recommend to apply the jet ID criteria listed below including those marked as "for LepVeto" for all analyses. For analyses that perform any special cleaning or selections between jets and leptons, the jet ID can also be applied without the vetoing on leptons to avoid possible biases.
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL

so no problem with using wp without "LepVeto" on it.

**Comment by mpresill** [comment]
> He confirmed the corresponding AK4's ID is similar to AK8's ID:
> 
> ```
> Please note: For AK8 jets, the corresponding (CHS or PUPPI) AK4 jet ID should be used. 
> ```
> 
> in https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL#Recommendations_for_the_13_T_AN1

Davide's old setting (jetid=0 - that should mean loose), is maybe not recommended: 
https://hypernews.cern.ch/HyperNews/CMS/get/jet-algorithms/608/1.html 
as they suggest to use:

```
 2016 (Loose, Tight, TightLepVeto)
 https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016
 2017 (Tight, TightLepVeto)
 https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2017
 2018 (Tight, TightLepVeto which for simplicity we removed the Tight, since there are no loose anymore)
 https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2018?rev=13

```

**Comment by SiewYan** [comment]
@mpresill , we should refer those parameter values here (at the declaration)[*] rather than the default values. Even though they are the same. (ok, we are on the same page : https://github.com/mpresill/LatinoAnalysis/issues/4#issuecomment-991154509)

For convenience, I states the bitwise operation rule here 
```
# bit1 : loose id / bit2 : tight id / bit3 : tightLepVeto
# if fatjet = loose && tight && tightLepVeto => 111(in binary) => 1+2+4 = 7
# (is loose id) + 2*(is tight id) + 4*(is tightLepVeto id)
# Jet ID flags bit1 is loose (always false in 2017 since it does not exist), bit2 is tight, bit3 is tightLepVeto
# >=2 -> ask tightId
# >=4 -> ask tightIdLepVeto
# >=6 -> ask tightId+tightIdLepVeto
```

Yielding bit value zero meant all tightId, tightIdLepVeto, and tightId+tightIdLepVeto are false; does it mean loose (which should be jetid = 1)?

[*] https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2871

**Comment by SiewYan** [comment]
> > He confirmed the corresponding AK4's ID is similar to AK8's ID:
> > ```
> > Please note: For AK8 jets, the corresponding (CHS or PUPPI) AK4 jet ID should be used. 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVUL#Recommendations_for_the_13_T_AN1
> 
> Davide's old setting (jetid=0 - that should mean loose), is maybe not recommended: https://hypernews.cern.ch/HyperNews/CMS/get/jet-algorithms/608/1.html as they suggest to use:
> 
> ```
>  2016 (Loose, Tight, TightLepVeto)
>  https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2016
>  2017 (Tight, TightLepVeto)
>  https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2017
>  2018 (Tight, TightLepVeto which for simplicity we removed the Tight, since there are no loose anymore)
>  https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2018?rev=13
> ```

It was jetid = 1; then it change to jetid=0 for no apparent reason[*]

* https://github.com/mpresill/LatinoAnalysis/commit/31d59fcc1532e6c1f59f0af945d46123dcca0c75#diff-c0667774b750db336db75b9ce8fbdf0c9ef9d8e4bb8fded6d9ad1d8cc2e32eb2

**Comment by SiewYan** [comment]
the JetSel module uses TightID [*] ; does it imply we should use TightID on fatjet correspondingly ?

[*] https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2814

**Comment by mpresill** [comment]
> the JetSel module uses TightID [*] ; does it imply we should use TightID on fatjet correspondingly ?
> 
> [*] https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2814

I think so, as far as I understand from a tons of HN pages, Tight should be fine for the three years Fjs. We will specify this on the PR to Latinos to be sure the others approve. OK?

**Comment by SiewYan** [comment]
Okies, before that, may i know do you happen to know why the old prescription is used (the current configuration)? Did you inherit it from someone or follow other group's recommendation?

**Comment by mpresill** [comment]
> Okies, before that, may i know do you happen to know why the old prescription is used (the current configuration)? Did you inherit it from someone or follow other group's recommendation?

I have tried asking Davide (who did this changes I guess), but is not replying me... Anyway, from old sync procedures with FNAL, I remember they complained about the FJ id we were using at re reco, so maybe it makes sense to change it....

**Comment by mpresill** [comment]
OK, got the apparent reason why there was jetid=0 in the past.
it was due to a bug in the nanoAODs Davide was reading at that time and could not use correct prescription.
=> I think we @SiewYan we can update the jet id to current prescription, what do you think?

**Comment by SiewYan** [comment]
@mpresill , you mean this https://github.com/mpresill/LatinoAnalysis/issues/5#issuecomment-991563048 ? then yeah, I agreed.

Following the same JetID for AK4: https://github.com/mpresill/LatinoAnalysis/blob/UL_production/NanoGardener/python/framework/Steps_cfg.py#L2808-L2816

**Comment by SiewYan** [comment]
PR: #7
